### ISSUE TITLE
Disabling "Send keys to all monitors" has no effect

### ISSUE THREAD

**Issue by fvisin** [alin23/Lunar#351]
# Issue details 
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro 2020

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell P2720DC

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to USB-C

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    No

# Issue description:
After disabling "Send keys to all monitors", when I press the brightness key the macbook display brightness changes regardless of which monitor my mouse pointer is on. I can control the external monitor brightness pressing ctrl+brightness key, so it seems that disabling "Send keys to all monitors" has no effect.

**Comment by alin23** [comment]
Yes, it was an oversight on my part for the single-display case. The fix has been pushed and will be released today or tomorrow

**Comment by fvisin** [comment]
Awesome, thank you for the quick reply!

**Comment by alin23** [comment]
This should be fixed in v4.1.0. Let me know if it still happens and I'll reopen this.

**Comment by fvisin** [comment]
This was not solved completely. I can now control the laptop monitor (independently from the external monitor) when the mouse pointer is on it, but when I try to change the brightness of the external monitor both are updated.

**Comment by alin23** [comment]
@fvisin Please make sure to read how hotkeys work now here: https://lunar.fyi/faq#hotkeys
There are still some edge cases that you need to know of

**Comment by fvisin** [comment]
In the Media keys preferences, I unchecked the box described as "If unchecked, the Brightness keys will only control the monitor where the cursor is placed.". I would expect the Brightness keys to only control the external monitor when the cursor is placed there. Is this incorrect?

**Comment by alin23** [comment]
Yes, that is correct, unless you use Sync Mode:

<img width="962" alt="Shot_Safari app_Lunar - Frequently Asked Questions_7tmy5YIV" src="https://user-images.githubusercontent.com/3819725/123622302-befb0700-d814-11eb-966d-8c34c91b94d0.png">

**Comment by fvisin** [comment]
Thanks for confirming! I am using the Manual mode, so I think the bug is still not completely solved. When the cursor is on the external monitor, Lunar controls both monitors.

**Comment by alin23** [comment]
Ok I'll double check this again. Thank for the details!

**Comment by fvisin** [comment]
Thank you for looking into it! Let me know if I can provide more information or logs.

**Comment by alin23** [comment]
Just to be sure, you have only one external monitor, and you're using a MacBook with the lid opened. Correct?

**Comment by fvisin** [comment]
That's correct.

**Comment by alin23** [comment]
In the last version I tried to remove the need for Accessibility permissions and make Lunar act as listen-only for media keys and only ask for Input Monitoring permissions. 

It seems this doesn't work as I thought. Lunar no longer has the ability to block media key events from reaching the system (for when you only need to control the external monitor)

I'll revert that change and release a fixed version today or tomorrow.

**Comment by fvisin** [comment]
I see. That makes sense, thank you. Thank you for the quick fix!

**Comment by alin23** [comment]
I fixed this in 4.3.0 but I took down the update for the moment because some users are experiencing some ugly issues in specific setups. 

You can still try 4.3.0 from the GitHub releases page to see if it fixes your issue and if you experience any weird behavior. 

I'll be working on trying to reproduce and fix the reported issues and hopefully have a 4.3.1 by the end of the week. 

Tracking down bugs that I never experience is close to impossible, I'm going to need all the help I can get from the users.

**Comment by fvisin** [comment]
I confirm this has been fixed in 4.5.1 - thank you!!

**Comment by alin23** [comment]
Thanks for the confirmation!
