### ISSUE TITLE
DDC logic needs update for M1 Pro and M1 Max

### ISSUE THREAD

**Issue by pszypowicz** [alin23/Lunar#416]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro 2021 M1 Pro

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    32UL950-W

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Sync

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    yes

# Issue description:
The DDC does not work. 

It used to work when connected with the same cable to the mac mini m1. Now, when connected to new macbook pro, only the "software controls" work. 

Please let me know if I can help debug it.

**Comment by gautamg795** [comment]
@alin23 would you mind posting a patch of the changes required to support the T600x change? I'm looking to port M1 series support to some Rust DDC libraries and your changes seem like a good place to start.

**Comment by alin23** [comment]
@gautamg795 in Lunar's case it was a simple matter of also iterating through the T600x ioreg tree and check the new dispext and dcp entries:

https://github.com/alin23/Lunar/blob/master/Lunar/Utils/DisplayController.swift#L638-L642

https://github.com/alin23/Lunar/blob/master/Lunar/Utils/DisplayController.swift#L662

https://github.com/alin23/Lunar/blob/master/Lunar/Utils/DisplayController.swift#L699

The previous IOAVService method used for M1 still works, I just had to look for the controllers in the new tree structure.

**Comment by alin23** [comment]
This is fixed in Lunar 5!

**Comment by samwzlim** [comment]
Hi, I have an M1 Pro as well and Hardware DDC does not work even connecting to an external monitor directly using a HDMI to HDMi cable. I have already tried all the troubleshooting steps in this thread but it still does not work :(

**Comment by alin23** [comment]
> Hi, I have an M1 Pro as well and Hardware DDC does not work even connecting to an external monitor directly using a HDMI to HDMi cable. I have already tried all the troubleshooting steps in this thread but it still does not work :(. I am using sync mode btw.
> 
> 
> 
> I am using the latest version of Lunar at the point of writing this.

@samwzlim unfortunately the HDMI port of the new MacBook Pro has the same limitation as the Mac Mini one. DDC is blocked in hardware. 

**Don't use the HDMI port of the new MacBook Pro if you want DDC. Use one of the Thunderbolt ports.**

**Comment by yunyu** [comment]
@alin23 I have a M1 Pro machine and DDC doesn't work through a thunderbolt to HDMI adapter. The exact same adapter and setup works with DDC when plugged into a M1 Macbook Air, but not with a M1 Pro 14 inch Macbook.

**Comment by alin23** [comment]
> @alin23 I have a M1 Pro machine and DDC doesn't work through a thunderbolt to HDMI adapter. The exact same adapter and setup works with DDC when plugged into a M1 Macbook Air, but not with a M1 Pro 14 inch Macbook.

Can you please activate Verbose Logging in [Advanced settings](https://app.lunar.fyi/advanced) on the M1 Pro that doesn't work?

Then do some connecting/disconnecting of the monitor cable as a test and some brightness changing from the Lunar UI (even if it's not working) and then send me the log from `~/Library/Caches/Lunar/swiftybeaver.log`

An ioreg dump would also be helpful: 

```sh
ioreg -r -l -c AppleT600xIO | gzip -9 > ~/Desktop/ioreg-m1pro.txt.gz
```

Then send the `ioreg-m1pro.txt.gz` that gets created on your desktop.

**Comment by yunyu** [comment]
@alin23 Here are the logs:

swiftybeaver.log: https://gist.github.com/b0beb94c5160f397e5dbade3c7c7265b
ioreg dump: https://transfer.sh/XYyvFr/ioreg-m1pro.txt.gz

Thanks in advance!

**Comment by alin23** [comment]
@yunyu thanks for the details!

It seems the problem is caused by the HDMI port detection logic. Because the HDMI port doesn't support DDC and can cause artifacts if DDC is used with monitors connected to that port, I tried to detect if that port is used and disable DDC on it.

While this worked fine on the Mac Mini, the MacBook has a much more different hardware tree and causes false positives in my detection.

Here's a beta with that detection disabled: https://files.lunar.fyi/Lunar-5.2.1-beta2.zip

If you have a HDMI-to-HDMI cable, could you help me with some more data to improve this detection?

It would be great if you could have both cables connected at the same time to the same monitor:
1. Connect the **HDMI-to-HDMI** cable to **HDMI1** of the monitor and the **built-in HDMI port** of the MacBook
2. Connect the **HDMI-to-USB-C** to **HDMI2** of the monitor and **one of the USB-C ports of the MacBook**
3. Switch monitor input to **HDMI1**
4. Dump the ioreg tree using the same command: `ioreg -r -l -c AppleT600xIO | gzip -9 > ~/Desktop/ioreg-m1pro.txt.gz`
